#ifndef DASM_INST_SET_H
#define DASM_INST_SET_H
#include "dasm_type.h"
#include "dasm_cpu.h"
#include "dasm_alu.h"

// General
void Nop(void);
void Display(void);

// A
void Load_A_Imm(void);
void Load_A_Adr(void);
void Store_A_Adr(void);
void Put_A(void);
void Pop_A(void);
void T_A_B(void);
void T_A_C(void);

// B
void Load_B_Imm(void);
void Load_B_Adr(void);
void Store_B_Adr(void);
void Put_B(void);
void Pop_B(void);
void T_B_A(void);
void T_B_C(void);

// C
void Load_C_Imm(void);
void Load_C_Adr(void);
void Store_C_Adr(void);
void Put_C(void);
void Pop_C(void);
void T_C_A(void);
void T_C_B(void);

// Operations
void Add_A_Imm(void);
void Add_A_Adr(void);
void Add_A_B(void);
void Add_A_C(void);
void Sub_A_Imm(void);
void Sub_A_Adr(void);
void Sub_A_B(void);
void Sub_A_C(void);
void Mul_A_Imm(void);
void Mul_A_Adr(void);
void Mul_A_B(void);
void Mul_A_C(void);
void And_A_Imm(void);
void And_A_Adr(void);
void And_A_B(void);
void And_A_C(void);
void Or_A_Imm(void);
void Or_A_Adr(void);
void Or_A_B(void);
void Or_A_C(void);
void Xor_A_Imm(void);
void Xor_A_Adr(void);
void Xor_A_B(void);
void Xor_A_C(void);
void Add_B_Imm(void);
void Add_B_Adr(void);
void Add_B_A(void);
void Add_B_C(void);
void Sub_B_Imm(void);
void Sub_B_Adr(void);
void Sub_B_A(void);
void Sub_B_C(void);
void Mul_B_Imm(void);
void Mul_B_Adr(void);
void Mul_B_A(void);
void Mul_B_C(void);
void And_B_Imm(void);
void And_B_Adr(void);
void And_B_A(void);
void And_B_C(void);
void Or_B_Imm(void);
void Or_B_Adr(void);
void Or_B_A(void);
void Or_B_C(void);
void Xor_B_Imm(void);
void Xor_B_Adr(void);
void Xor_B_A(void);
void Xor_B_C(void);
void Add_C_Imm(void);
void Add_C_Adr(void);
void Add_C_B(void);
void Add_C_A(void);
void Sub_C_Imm(void);
void Sub_C_Adr(void);
void Sub_C_B(void);
void Sub_C_A(void);
void Mul_C_Imm(void);
void Mul_C_Adr(void);
void Mul_C_B(void);
void Mul_C_A(void);
void And_C_Imm(void);
void And_C_Adr(void);
void And_C_B(void);
void And_C_A(void);
void Or_C_Imm(void);
void Or_C_Adr(void);
void Or_C_B(void);
void Or_C_A(void);
void Xor_C_Imm(void);
void Xor_C_Adr(void);
void Xor_C_B(void);
void Xor_C_A(void);
void Not_A(void);
void Not_B(void);
void Not_C(void);
void Not_Adr(void);
void Left_Shift_A(void);
void Right_Shift_A(void);
void Left_Shift_B(void);
void Right_Shift_B(void);
void Left_Shift_C(void);
void Right_Shift_C(void);
void Left_Shift_Adr(void);
void Right_Shift_Adr(void);
void Inc_A(void);
void Inc_B(void);
void Inc_C(void);
void Inc_Adr(void);
void Dec_A(void);
void Dec_B(void);
void Dec_C(void);
void Dec_Adr(void);

// Jumps
void Jump_Rel_Imm(void);
void Jump_Abs(void);
void Jump_Zero(void);
void Jump_Over(void);
void Jump_Under(void);
void Jump_Greater(void);
void Jump_Less(void);
void Jump_Equal(void);

void Store_Imm_Adr(void);
void Send(void);

#endif